services:
  db:
    image: postgres:16
    container_name: sehbmaster-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    # ❌ entferne diese Zeile:
    # ports:
    #   - "5432:5432"
    # ✅ optional: nur intern sichtbar machen
    expose:
      - "5432"
    networks:
      - private

  backend:
    build:
      context: ./backend
    container_name: sehbmaster-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INGEST_API_KEY=${INGEST_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    ports:
      - "8000:8000"
    networks:
      - private
      - default

  web:
    build:
      context: ./streamlit
    container_name: sehbmaster-web
    restart: unless-stopped
    env_file: .env
    environment:
      - API_BASE=${API_BASE:-http://backend:8000/api}
    depends_on:
      - backend
    ports:
      - "80:8501"
    networks:
      - default

volumes:
  db_data:

networks:
  private:
    driver: bridge
    internal: true
